apiVersion: v1
kind: Service
metadata:
  name: vue-webapp
  labels:
    run: vue-webapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: vue-webapp
  type: NodePort